config/routes.rb
Commenter::Application.routes.draw do

  root 'projects#index'
  

  

  resources :projects do
	resources :comments
  end

    

end

app/models/comment.rb
class Comment < ActiveRecord::Base

	belongs_to :project

	validates :body, uniqueness: true
	
	validates :body, :project_id, presence: true
	
	
	include Workflow
	
	workflow do
		    state :open do
		      event :close, :transitions_to => :closed
		    end
	      
		    state :closed do
		      event :reopen, :transitions_to => :open
		    end
	end


	def created_on_day
		self.created_at.to_date
	end
	
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :comments, dependent: :destroy

	validates :name, uniqueness: true
	validates :name, uniqueness: true
	
	validates :name, presence: true
	
	def items
		comments
	end
	
	
	def done?
		items.where('workflow_state = ?', 'open').size == 0
	end
	
	
	def recent_items
		items.where('created_at > ?',  Date.yesterday.to_time.utc)
	end
	
	
	def items_by_day
		items.group_by &:created_on_day
	end
	
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
	
	before_action :load_project 
	
	def new
		@comments = comments.order("workflow_state ASC").order("created_at DESC")
	end
	
	#<%= render @project.comments %> 
	def create    
		@comment = comments.new(comment_params)    
		if @comment.save      
			respond_to do |format|        
				format.html { redirect_to @project, notice: 'Thanks for your comment' }        
				format.js      
			end    
		else      
			respond_to do |format|        
				format.html { redirect_to @project, alert: 'Unable to add comment' }        
			        format.js { render 'fail_create.js.erb' }      
			end   
		end  
	end
	
	def update
		c=Comment.find(params[:id])
		@comment= switch_state(c) 
		@link='#comment_'+@comment.id.to_s
		@project_status_link = @project.name+'_status'
		@project_status = @project.done?
		@comments = load_project.items
		@opencomments=   @comments.where('workflow_state = ?', 'open').order("created_at DESC") 
		@closedcomments= @comments.where('workflow_state = ?', 'closed').order("created_at DESC") 
		respond_to do |format|  
			if @comment.current_state == 'open'
					 format.js { render 'update_opencomments.js' }       
			else
					 format.js { render 'update_closedcomments.js' }       
			end
		end
	end

  private  
  
	def switch_state(c)
		(c.workflow_state == 'open')? c.update_attribute(:workflow_state, 'closed') : c.update_attribute(:workflow_state, 'open')
		c
	end
		
	def load_project    
		@project = Project.find(params[:project_id])  
	end  
	
	def comments
		@comments= @project.comments
	end
	
	def comment_params    
		params.require(:comment).permit(:body)  
	end
	
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	
	def index
		@projects = Project.all
	end
	
	def new
		@project= Project.new
	end
	
	def show
		@comments = get_project.comments
		@opencomments= 	@comments.where('workflow_state = ?', 'open').order("created_at DESC") 
		@closedcomments= @comments.where('workflow_state = ?', 'closed').order("created_at DESC") 
	end
	
	def create
		@project = Project.new(project_params) 
		

		if @project.save    
			flash[:notice] = "Project has been created."    
			redirect_to :root
		else    
			 flash[:error]= "Error while saving #{@project.name}."
			 redirect_to :back
		end
		   
	end
	   
  def destroy
    get_project.destroy
    flash[:notice] = "Project #{@project.name} has been deleted."
    redirect_to :root
  end

private 

	def get_project    
		@project = Project.find(params[:id])  
	end  
  
  def project_params    
	  params.require(:project).permit(:name, :description)  
	  end
	
end

app/helpers/application_helper.rb
module ApplicationHelper


	def event_for(comment)
		return {:label => 'Close', :event => :close} if comment.current_state == 'open'
		return {:label => 'Repopen', :event => :reopen }
	end

	def replace_empty_with(e, s)
		return s if e.nil? or e.blank?
		return e
	end
	
	def label_for(done)
		 labels={:inprogress => "label label-default", :done => "label label-primary", :empty => "label label-default"}
		 return labels[:done] if done
		 return labels[:inprogress]
	end

	
	def 	project_details(p)
		return 'Empty' if p.comments.empty?
		return 'Done' if p.done?
		return 'In Progress'
	end
	
	def map_to_bootstrap_class(k)
	b= {:notice => "alert alert-warning", :error => "alert alert-danger"}
	return b[k.to_sym]
	end
	
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/comments/_comment.html.erb
 

<%= content_tag_for(:tr, comment) do %>
  <td id="#{'edit_comment_link'+comment.id.to_s}">	<%= comment.body %>		</td>
  <td id="#{'edit_comment_link'+comment.id.to_s}">	<%= comment.created_on_day %> </td>  
  <td id="#{'edit_comment_link'+comment.id.to_s}">	<%= comment.workflow_state %></td>
  <td id="#{'edit_comment_link'+comment.id.to_s}">	 <%= link_to event_for(comment)[:label],  [@project, comment],  :format => :js, :remote => true, :method=> :put %> </td>
<% end %>
 

app/views/comments/_header_comment_table.html.erb
<tr>
	<th>
		Body
	</th>
	<th>
		Created_at
	</th>
	<th>
		State
	</th>
	<th>
		Actions
	</th>		
</tr>

app/views/comments/_showmodal.html.erb
 <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
    <h3 id="myModalLabel">Modal header</h3>
  </div>
  

  <div class="modal-body">
    **here comes whatever you want to show!**
  </div>
  
   <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <button class="btn btn-primary">Save changes</button>
  </div>
  
  
<input type="button" id="tstModal"/>
<div class="modal">
<!--Some modal content here -->
</div>

<script type="text/javascript">
$(document).ready(function() {
$("#tstModal").click(function() {
     $(".modal").modal("show");
});
});
</script>

app/views/comments/new.html.erb
<%= form_for([@project, @project.comments.new], remote: true) do |f| %>  

<div class="field">    
    	<%= f.label 'Comment' %><br />
	<%= f.text_field :body, size: 200 %>  
</div>

<div class="actions">    
	<%= f.submit 'Create Comment' %>  
</div> 

<% end %>

app/views/comments/update.js.erb
$('#opencomments').append("<%= escape_javascript(render(@comment)) %>"); 
$("<%= @link %>")[0].reset();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Commenter</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1>Commenter</h1>

<%= link_to 'Projects', projects_path %>

<div>
<% if !flash.empty? %>
<div id="flash"> 
    <% flash.keys.each do |k| %> 
        <div class="<%= map_to_bootstrap_class(k) %>">
            <%= flash[k] %>
        </div>  
    <% end %>   
</div>
   <% end %>   
</div>

<%= yield %>

</body>
</html>

app/views/projects/index.html.erb
</br>
</br>
<%= link_to 'New Project', new_project_path, :class =>"btn btn-default" %>

</br>
</br>

<table class="table">
<thead>Available Projects</thead>
<tr>
<th>ID</th>
<th>Name</th>
<th>Description</th>
<th>State</th>
<th>Actions</th>
</tr>

	<% @projects.each do |project| %>
		<tr>
			<td>
				<%= project.id%>
			</td>
			<td>
				<%= link_to project.name, project_path(project) %>
			</td>
			<td>
				<%=  truncate(replace_empty_with(project.description, '-')   , length: 25, omission: '... (continued)' )  %>
			</td>
			<td>
				<%= project_details(project)%>
			</td>
			<td>
				<%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %>
			</td>
		</tr>
	<% end %>

</table>

app/views/projects/new.html.erb
</br>
</br>
<h2> New Project </h2>

<%= form_for(@project) do |f| %>

<p>
<%= f.label :name %>
<%= f.text_field :name, size: 200 %>
</p>

<p>
<%= f.label :description %>
<%= f.text_field :description, size: 200 %>
</p>


<%= f.submit 'Create a Project', :class=> "btn btn-default" %>

<% end %>

app/views/projects/show.html.erb
</br>

<h2> Project:  <%=  @project.name %>
<h3 class="project_description">  Description:  <%= replace_empty_with(@project.description, '-') %> </h3>
<h3 class="project_status">  Status:  <span class="<%= label_for( project_details(@project) )  %>" >  <%= project_details(@project) %></span> </h3>


<div class="panel panel-default" id="comments">  
		<table class="table" id="opencomments">
			<caption>Open Comments</caption> 
			<%= render '/comments/header_comment_table' %>
			<%= render @opencomments %> 
		</table>	
</div>

<%= link_to "New Comment", new_project_comment_path(@project, :format => :js), :remote => true, :id => 'new_comment_link', :class => "btn btn-default" %> 

</br>
</br>

<div  class="panel panel-default" id="closed_comments">  
		<table class="table" id="closedcomments">
			<caption>Closed Comments</caption> 
			<%= render '/comments/header_comment_table' %>
			<%= render @closedcomments %> 		
		</table>
</div>